// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace BeerBot.BeerApiClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Beer
    {
        /// <summary>
        /// Initializes a new instance of the Beer class.
        /// </summary>
        public Beer()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Beer class.
        /// </summary>
        public Beer(int? id = default(int?), int? breweryId = default(int?), string name = default(string), int? categoryId = default(int?), int? styleId = default(int?), double? abv = default(double?), double? ibu = default(double?), double? srm = default(double?), string description = default(string))
        {
            Id = id;
            BreweryId = breweryId;
            Name = name;
            CategoryId = categoryId;
            StyleId = styleId;
            Abv = abv;
            Ibu = ibu;
            Srm = srm;
            Description = description;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "breweryId")]
        public int? BreweryId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "categoryId")]
        public int? CategoryId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "styleId")]
        public int? StyleId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "abv")]
        public double? Abv { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ibu")]
        public double? Ibu { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "srm")]
        public double? Srm { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

    }
}
