// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace BeerBot.BeerApiClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Brewery
    {
        /// <summary>
        /// Initializes a new instance of the Brewery class.
        /// </summary>
        public Brewery()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Brewery class.
        /// </summary>
        public Brewery(int? id = default(int?), string name = default(string), string address1 = default(string), string address2 = default(string), string city = default(string), string state = default(string), string code = default(string), string country = default(string), double? latitude = default(double?), double? longitude = default(double?), string accuracy = default(string), string phone = default(string), string website = default(string), string description = default(string))
        {
            Id = id;
            Name = name;
            Address1 = address1;
            Address2 = address2;
            City = city;
            State = state;
            Code = code;
            Country = country;
            Latitude = latitude;
            Longitude = longitude;
            Accuracy = accuracy;
            Phone = phone;
            Website = website;
            Description = description;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address1")]
        public string Address1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address2")]
        public string Address2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "city")]
        public string City { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "state")]
        public string State { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "code")]
        public string Code { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "country")]
        public string Country { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "latitude")]
        public double? Latitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "longitude")]
        public double? Longitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accuracy")]
        public string Accuracy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "phone")]
        public string Phone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "website")]
        public string Website { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

    }
}
