// <auto-generated>
// Code generated by LUISGen .\BeerBotLuisModel.json -cs BeerBot.BeerBotLuisModel -o .
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
namespace BeerBot
{
    public class BeerBotLuisModel: Microsoft.Bot.Builder.Core.Extensions.IRecognizerConvert
    {
        public string Text;
        public string AlteredText;
        public enum Intent {
            Bye, 
            GetHelp, 
            Greet, 
            None, 
            OrderBeer, 
            RandomBeer, 
            RecommendBeer
        };
        public Dictionary<Intent, Microsoft.Bot.Builder.Ai.LUIS.IntentData> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] beername;

            // Lists
            public string[][] chaser;
            public string[][] sidedish;

            // Composites
            public class _Instancebeerorder
            {
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] beername;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] chaser;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] sidedish;
            }
            public class beerorderClass
            {
                public string[] beername;
                public string[][] chaser;
                public string[][] sidedish;
                [JsonProperty("$instance")]
                public _Instancebeerorder _instance;
            }
            public beerorderClass[] beerorder;

            // Instance
            public class _Instance
            {
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] beername;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] chaser;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] sidedish;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] beerorder;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<BeerBotLuisModel>(JsonConvert.SerializeObject(result));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score;
                }
            }
            return (maxIntent, max);
        }
    }
}
